### PR TITLE
parser: result column bug: can take expr of single and recursive type.

### LINKED ISSUE #151: parser: parse expression cannot parse functions
**Describe the bug**
The parser can not follow the function production rule `function-name ( expr )`.

**To Reproduce**
Try to parse `SELECT AVG(price) AS average_price FROM items LEFT INNER JOIN prices`.

**Expected behavior**
`AVG` is clearly a literal, however, it must be stored in `function-name` instead of `literal-value`, because it is followed by an opening parenthesis.

### PR DESCRIPTION
**Pull request by SUMUKHA-PK**
Fixes #151, is a part of #153.

Fixes bug in result column, can take single and recursive expr.

Added test for proof.

### CODE REVIEW

**Comment by TimSatke** [comment]
Is this the quick fix for the functions?

**Comment by SUMUKHA-PK** [comment]
This is quite a complete fix for `ResultColumn` not only `Function-name`.

#153 was opened to make sure this is globally true.

File: internal/parser/simple_parser_rules.go [hunk 1]
```diff
@@ -3731,11 +3752,17 @@ func (p *simpleParser) parseResultColumn(r reporter) (stmt *ast.ResultColumn) {
...
 			}
 		} else {
+			// Conditions for recursive expressions or single expressions.
 			recExpr := p.parseExprRecursive(&ast.Expr{LiteralValue: tableNameOrAsteriskOrExpr}, r)
 			if recExpr != nil {
 				stmt.Expr = recExpr
 			} else {
-				stmt.Expr = &ast.Expr{LiteralValue: tableNameOrAsteriskOrExpr}
+				singleExpr := p.parseExprBeginWithLiteral(tableNameOrAsteriskOrExpr, r)
+				if singleExpr != nil {
```
Comment (TimSatke) [inline internal/parser/simple_parser_rules.go:3761]:
```suggestion
				if singleExpr := p.parseExprBeginWithLiteral(tableNameOrAsteriskOrExpr, r); singleExpr != nil {
```

Comment (TimSatke) [reply internal/parser/simple_parser_rules.go:3761]: just a suggestion

**Comment by SUMUKHA-PK** [comment]
Also, `LEFT OUTER JOIN` is not allowed. Only `LEFT JOIN` or `LEFT INNER JOIN` is.
Ref: https://sqlite.org/syntax/join-operator.html

File: internal/parser/simple_parser_rules.go [hunk 2]
```diff
@@ -1285,6 +1285,27 @@ func (p *simpleParser) parseExprRecursive(expr *ast.Expr, r reporter) *ast.Expr
...
 
+// parseExprBeginWithLiteral parses possible expressions that begin with a literal.
+// A nil is returned if it turns out not to be an expression.
+func (p *simpleParser) parseExprBeginWithLiteral(literal token.Token, r reporter) (expr *ast.Expr) {
+	expr = &ast.Expr{}
+	next, ok := p.optionalLookahead(r)
+	if !ok || next.Type() == token.EOF || next.Type() == token.StatementSeparator {
+		return nil
+	}
+	if next.Value() == "." {
```
[the remark this answers is not in the document]
Comment (SUMUKHA-PK) [reply internal/parser/simple_parser_rules.go:1295]: There are two possibilities we are interested in `.` and `(` in the next block. So this would be fine.

File: internal/parser/simple_parser_rules.go (hunk 1 above)
Comment (SUMUKHA-PK) [reply internal/parser/simple_parser_rules.go:3761]: Sure, but this is an inconsistency in our code base.

Comment (SUMUKHA-PK) [reply internal/parser/simple_parser_rules.go:3761]: Some are of this type and some are the traditional ones.

File: internal/parser/simple_parser_rules.go [hunk 3]
```diff
@@ -1301,6 +1300,7 @@ func (p *simpleParser) parseExprBeginWithLiteral(literal token.Token, r reporter
 		returnExpr := p.parseExprRecursive(&ast.Expr{LiteralValue: literal}, r)
 		if returnExpr != nil {
 			expr = returnExpr
+			return
 		}
 		return nil
```
Comment (TimSatke) [inline internal/parser/simple_parser_rules.go]:
```suggestion
		return returnExpr
```

Comment (SUMUKHA-PK) [reply internal/parser/simple_parser_rules.go]: Well both are same aren't they :D

Comment (TimSatke) [reply internal/parser/simple_parser_rules.go]: That's why you should change it

Comment (SUMUKHA-PK) [reply internal/parser/simple_parser_rules.go]: Can you request the change again? I can commit directly from here.

Comment (SUMUKHA-PK) [reply internal/parser/simple_parser_rules.go]: I switched OS's thats why :D

Comment (TimSatke) [reply internal/parser/simple_parser_rules.go]: It's still there (?)

File: internal/parser/simple_parser_rules.go [hunk 4]
```diff
@@ -1285,6 +1285,27 @@ func (p *simpleParser) parseExprRecursive(expr *ast.Expr, r reporter) *ast.Expr
...
+		return p.parseExpr2(literal, nil, nil, r)
+	} else if next.Type() == token.Delimiter && next.Value() == "(" {
+		return p.parseExpr5(literal, r)
+	} else {
+		returnExpr := p.parseExprRecursive(&ast.Expr{LiteralValue: literal}, r)
+		if returnExpr != nil {
+			expr = returnExpr
+			return
+		}
+		return nil
```
Comment (TimSatke) [inline internal/parser/simple_parser_rules.go:1305]:
```suggestion
		return returnExpr
```

Comment (TimSatke) [reply internal/parser/simple_parser_rules.go:1305]: Does it work this time?

**Comment by SUMUKHA-PK** [comment]
Done done
